docs: add category to each page (#171)
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] |
:---:|

## 🧰 Changes

It appears that the rdme docs sync step of our release CI is failing: https://github.com/readmeio/markdown/runs/2833856744

```
Error: We couldn't save this doc (Path `category` is required.).
```
This commit adds the category in the front-matter of each page we're syncing! I have some doc updates in the pipeline (will open a separate PR for them!) but wanted to make sure this was resolved first.

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].


[demo]: https://markdown-pr-171.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io